# Generated by Django 4.1.2 on 2022-10-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitelinks", "0002_alter_codeforceslink_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeforceslink",
            name="last_created_submission_id",
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name="codeforceslink",
            name="last_created_submission_time",
            field=models.BigIntegerField(default=-1),
        ),
    ]
