# Generated by Django 4.1.2 on 2022-10-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="coins",
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="freezes",
            field=models.IntegerField(default=0),
        ),
    ]
