# Generated by Django 4.1.2 on 2022-10-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_userinfo_coins_userinfo_freezes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="coins",
            field=models.IntegerField(default=0),
        ),
    ]
