# Generated by Django 4.1.2 on 2022-10-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="memory_taken",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="submission",
            name="submission_id",
            field=models.CharField(default=-1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="submission",
            name="time_taken",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
