# Generated by Django 4.1.2 on 2022-10-28 06:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("problems", "0003_submission_submission_time_submission_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="submission_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 28, 17, 51, 33, 321869)
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
