# Generated by Django 4.1.2 on 2022-10-29 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0004_alter_submission_submission_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="problem",
            name="tags",
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submission_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 29, 14, 32, 6, 210261)
            ),
        ),
    ]
