# Generated by Django 4.1.2 on 2022-10-29 03:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0005_problem_name_problem_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="tags",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submission_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 29, 14, 34, 46, 99933)
            ),
        ),
    ]
