# Generated by Django 4.1.2 on 2022-10-29 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0006_alter_problem_tags_alter_submission_submission_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="submission_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 29, 15, 37, 8, 247780)
            ),
        ),
    ]
