# Generated by Django 4.1.2 on 2022-10-29 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0008_alter_submission_submission_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submission_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 29, 20, 16, 17, 34470)
            ),
        ),
    ]
