# Generated by Django 4.1.2 on 2022-11-03 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0009_alter_problem_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="memory_taken",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="submission",
            name="result",
            field=models.CharField(default="OK", max_length=48),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submission_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 3, 13, 6, 20, 734179)
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="time_taken",
            field=models.IntegerField(default=0),
        ),
    ]
