# Generated by Django 4.1.2 on 2022-11-21 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0010_alter_submission_memory_taken_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="submission_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 21, 19, 6, 54, 974235)
            ),
        ),
    ]
